// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol KeysGlobalProtocol {
}

public protocol KeysEnvironmentProtocol {
    var spotifyClientID: String { get }
    var spotifyClientSecret: String { get }
}
